'use client';
import { useState } from 'react';
import { ArrowDownToLine, ChevronRight, Info } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Table, TableHeader, TableHead, TableBody, TableRow, TableCell } from '@/components/ui/table';
import { fmt, points, stats, type Point } from '@/lib/sweep';

const quality: Record<string, string> = { GRID_PASS: 'Grid check passed', GRID_FAIL: 'Grid check failed', FINE_MESH_ADOPTED: 'Grid-checked envelope', NOT_CHECKED: 'Not grid-checked' };

export function DataMethod({ mach }: { mach: number }) {
  const [showAll, setShowAll] = useState(false);
  const [selected, setSelected] = useState<Point | null>(null);
  const rows = points.filter(p => showAll || p.mach === mach);
  return <>
    <section className="panel"><div className="panel-head"><div><h2>Source data</h2><p>{showAll?`All ${stats.of + stats.ss} fine-mesh means`:`Mach ${mach.toFixed(2)} · ${rows.length} fine-mesh means`} · select a row for provenance</p></div><Button variant="outline" onClick={()=>setShowAll(!showAll)}>{showAll?'Selected Mach':'Show all Machs'}</Button></div><div className="source-table"><Table><TableHeader><TableRow>{['Solver','Mach','δ','Mroll · N·m','Cl','Myaw · N·m','Cn','Quality'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(p=><TableRow key={p.id} className="source-row" onClick={()=>setSelected(p)}><TableCell><button className="source-button" onClick={e=>{e.stopPropagation();setSelected(p);}}>{p.solver}<ChevronRight size={13}/></button></TableCell><TableCell>{p.mach.toFixed(2)}</TableCell><TableCell>{p.angle}°</TableCell><TableCell>{fmt(p.roll,6)}</TableCell><TableCell>{fmt(p.cl,6)}</TableCell><TableCell>{fmt(p.yaw,6)}</TableCell><TableCell>{fmt(p.cn,6)}</TableCell><TableCell><span className={`quality ${p.flags.length?'flagged':''}`}>{quality[p.verificationStatus]}{p.method === 'transient' ? ' · transient' : ''}{p.flags.length ? ' · source flagged' : ''}</span></TableCell></TableRow>)}</TableBody></Table></div>
    {selected&&<div className="source-detail"><div className="source-title"><strong>{selected.solver} · M{selected.mach.toFixed(2)} · {selected.angle}°</strong><Button size="sm" variant="ghost" onClick={()=>setSelected(null)}>Close</Button></div><p>{selected.mesh} {selected.note&&`· ${selected.note}`}</p><div className="source-stats"><span>Raw roll scatter <b>{fmt(selected.rawStdPct,2)}%</b></span><span>Block-mean scatter <b>{fmt(selected.blockStdPct,2)}{selected.blockStdPct==null?'':'%'}</b></span><span>Reported roll drift <b>{fmt(selected.driftPct,2)}%</b></span><span>Averaging samples <b>{selected.meanWindow}</b></span></div><p>{selected.flags.length?selected.flags.join(' · '):'No flags recorded by the source extractor. This is not a physical-validation certificate.'}</p><p><strong>Verification:</strong> {selected.verificationNote}</p><code>{selected.source}</code><p className="fineprint">SHA-256: {selected.sha256}</p>{selected.run&&<p>SimScale run: <code>{selected.run}</code></p>}</div>}</section>
    <div className="method-grid"><section className="panel method"><div className="eyebrow">01 / NORMALIZATION</div><h2>One reference system</h2><div className="math-block">q = ½ρV²<br/>Cl = Mroll / (q Sref Dref)<br/>Cn = Myaw / (q Sref Dref)<br/>Cm = Mpitch / (q Sref Dref)<br/>CA = −Fz / (q Sref)<br/>CY = Fy / (q Sref) · CN = Fx / (q Sref)</div><p>ρ = 1.18915 kg/m³ · Sref = 0.0026248 m² · Dref = 0.05781 m. Source velocities are used: Mach × 339.1, rounded to 0.1 m/s; 305 m/s at M0.90; 406.9 m/s at M1.2.</p><p><strong>Cl is roll coefficient (lowercase l).</strong> CN is normal force; Cn is yaw moment. Axial force corresponds to drag along the aligned freestream used here.</p></section>
    <section className="panel method"><div className="eyebrow">02 / AXES & YAW</div><h2>Moments at z = 0.330 m</h2><div className="math-block">Mroll = −Mz<br/>Myaw,0.330 = Mx,0.399 − 0.069 Fy<br/>Mpitch,0.330 = My,0.399 + 0.069 Fx</div><p>Body axis is z: nose +z, flow −z. Roll is about −z; yaw about +x; pitch about +y. The same force-based moment shift is applied to both solvers.</p><p>Yaw is shown signed. Calling it “adverse” requires a defined commanded turn direction; the CFD sweep alone establishes yaw coupling, not the vehicle’s flight response.</p></section>
    <section className="panel method"><div className="eyebrow">03 / REGRESSION</div><h2>Linear fits, with an intercept</h2><div className="math-block">y = aδ + b<br/>a = Σ(δ − δ̄)(y − ȳ) / Σ(δ − δ̄)²<br/>b = ȳ − aδ̄<br/>a per radian = a per degree × 180/π</div><p>Ordinary least squares, equally weighted source means, separately at each Mach. Both solvers use identical eligible angles. At M0.90, only OpenFOAM is fitted, and its 15° and −6° points are transient means. At least three points are required.</p><p>R² measures linearity. RMSE measures residual fit error; slope SE is the ordinary regression standard error, not CFD uncertainty. A full-range slope is an interval average, not a local derivative at zero.</p></section>
    <section className="panel method"><div className="eyebrow">04 / DATA QUALITY</div><h2>Grid check and flags</h2><p><strong>OpenFOAM M0.30–0.85: fine mesh adopted.</strong> Refining the background grid changed roll by ≤1.5 % at three corners (3°/M0.30, 10°/M0.60, 15°/M0.85). SimScale passes at 15°/M0.85 but fails at 3°/M0.30. M0.90 and M1.2 are outside the check. Axial force is grid-sensitive (1–3 % local, 7.7 % on SimScale at 15°/M0.85).</p><p><strong>Default fits include flagged means.</strong> The optional filter removes a condition from both solvers if either source flagged it. Flags are preserved as recorded, not treated as equivalent convergence tests.</p><p>OpenFOAM steady means average iterations 1,500–2,000 (501 samples) and report raw iteration scatter, which is 3–10 % at low Mach (the “noisy” flags) while the mean drifts under 1 %. SimScale means average the last 1,500 of 3,000 iterations and report the scatter of 250-iteration block means (worst 0.36 % off 0°). These statistics are not interchangeable.</p><p>The 0° rows are near zero on both solvers, so their percent scatter and drift are huge; those flags are expected, not failures. Transient means report the scatter over their time window (≤0.13 %).</p></section></div>
    <section className="panel method"><div className="eyebrow">05 / SCOPE & PROVENANCE</div><h2>The sealed-tab sweep (v5)</h2><p>Sealed-tab CAD exported 11 September 2026: tab widened to 8 mm (slot width) with the spanwise end clearances filled; the 1 mm chordwise gap remains so the tab can swing. Open pressure-outlet sides, fine per-deflection meshes (~1.5 M cells local, ~1.6 M SimScale). OpenFOAM: local rhoSimpleFoam v2606. SimScale: compressible steady solver. Both use SST and second-order momentum convection; their meshes and gradient discretizations are not identical.</p><p>OpenFOAM contributes {stats.of} means (8 deflections × M0.30–0.90). At M0.90 the 15° and −6° steady means drifted, so 15 ms transient restarts replace them; the superseded steady means stay visible under Transonic & M1.2. SimScale contributes {stats.ss} means (8 deflections × M0.30–0.85). A 15° / M1.2 case exists for OpenFOAM only and is kept outside the fits.</p><div className="notice context-note"><Info size={18}/><span><strong>The previous sweep is archived, not mixed in.</strong> The 4 Sep CAD sweep (1 mm end clearances) is compared point by point under Sealed vs previous and its data stays downloadable. No previous value enters these fits.</span></div><p>The source JSON files are frozen with SHA-256 checksums in the source manifest. This is a saved snapshot, not a live SimScale or solver feed. Solver agreement and a grid check do not, by themselves, establish real-world accuracy.</p><div className="download-row"><a href="/data/normalized.csv" download>Normalized data <ArrowDownToLine size={14}/></a><a href="/data/fits.csv" download>All fit coefficients <ArrowDownToLine size={14}/></a><a href="/data/comparison.csv" download>Paired comparisons <ArrowDownToLine size={14}/></a><a href="/data/manifest.json" download>Source manifest <ArrowDownToLine size={14}/></a><a href="/data/previous-sweep.csv" download>Sealed vs previous <ArrowDownToLine size={14}/></a></div></section>
  </>;
}
